# Generated by Django 4.0.6 on 2022-07-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=4,
                verbose_name="Preço do Produto",
            ),
            preserve_default=False,
        ),
    ]
